// AUTO-GENERATED by scripts/generate-protocol.ts from src/protocol-registry.json.
// DO NOT EDIT BY HAND — 手改会被 verify:protocol / 测试判漂移。重新生成: npm run generate:protocol

export const CLUE_STATUSES = ["proposed", "open", "in_flight", "explored", "dropped", "blocked"] as const;
export const DOC_KINDS = ["transcript", "report", "argument"] as const;

export const CLUE_FIELDS = ["assignee", "depth", "parent", "rationale", "run_id", "sources", "status", "text"] as const;
export const EVIDENCE_FIELDS = ["anchor", "claim", "clue_id", "quote"] as const;
export const DOC_FIELDS = ["body", "digest", "doc_kind", "origin"] as const;

export const CLUE_REQUIRED = ["depth", "sources", "status", "text"] as const;
export const EVIDENCE_REQUIRED = ["anchor", "claim", "clue_id", "quote"] as const;
export const DOC_REQUIRED = ["body", "digest", "doc_kind", "origin"] as const;

export const CLUE_TRANSITIONS = {
  "proposed": ["open", "dropped"],
  "open": ["in_flight", "blocked"],
  "in_flight": ["explored", "open", "blocked"],
  "explored": [],
  "dropped": [],
  "blocked": [],
} as const;
